### ISSUE TITLE
 Duplicate class error

### ISSUE THREAD

**Issue by CharlyKeleb** [LeGoffMael/video_editor#153] opened 2023-05-31 11:51 UTC
This error occurs when you use video_editor plugin and ffmpeg_kit_flutter 

`Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.arthenica.ffmpegkit.Abi found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.AbiDetect found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.AbstractSession found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.AsyncFFmpegExecuteTask found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.AsyncFFprobeExecuteTask found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.AsyncGetMediaInformationTask found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.BuildConfig found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.CameraSupport found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Chapter found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegKit found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegKitConfig found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegKitConfig$1 found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegKitConfig$2 found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegKitConfig$SAFProtocolUrl found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegSession found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegSessionCompleteCallback found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFprobeKit found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFprobeSession found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFprobeSessionCompleteCallback found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Level found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Log found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.LogCallback found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.LogRedirectionStrategy found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.MediaInformation found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.MediaInformationJsonParser found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.MediaInformationSession found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.MediaInformationSessionCompleteCallback found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.NativeLoader found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Packages found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.ReturnCode found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Session found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.SessionState found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Signal found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Statistics found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.StatisticsCallback found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.StreamInformation found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-min-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-min-gpl:5.1)
`

**Comment by LeGoffMael** [comment] 2023-06-23 06:34
duplicate of #129

**Closed as completed by LeGoffMael** 2023-06-23 06:34 UTC
