### ISSUE TITLE
Exception when run the project

### ISSUE THREAD

**Issue by DarkSide-69** [LeGoffMael/video_editor#112] opened 2022-11-01 16:38 UTC
When I try to run the project I got this error: (but when I remove the package the app runs normally)

![2022-11-01_181540](https://user-images.githubusercontent.com/104450230/199287413-571b591c-d0b0-4bb0-8d93-8506928da19a.png)

**Comment by LeGoffMael** [comment] 2022-11-03 10:09
Duplicate of #37, are you using an emulator ?

**Comment by DarkSide-69** [comment] 2022-11-03 10:33
No.
but I solved it, I guess cause I was using jdk 1.8 but when I upgraded it to jdk 11 the project ran.

**Closed as completed** 2022-11-03 10:34 UTC
Labels: question

**Comment by LeGoffMael** [comment] 2022-11-03 12:02
thanks for the update!
